server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8081

spring:
  datasource:
    password: 1234
    url: jdbc:mysql://localhost:3306/evote?serverTimezone=UTC
    username: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 25
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


